---
- hosts: 172.31.87.23
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to install web srever
    apt:
     name: apache2
     state: present
    notify:  restartwebserver

  - name: i want to copy indexfile into ansible node side
    template:
     src: myindex.j2 
     dest: /var/www/html/index.html
    notify: restartwebserver 
    
  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted   